name: webui_tasks
version: 0.0.2
author: Damon Douglas <douglas.damon@gmail.com>
description: A webui task library based on Hop.
homepage: https://github.com/damondouglas/webui_tasks.dart
dependencies:
  html5lib: '>=0.4.3 <0.4.4'
  bot: '>=0.20.1 <0.20.2'
  web_ui:
    git:
      ref: ce921b1a96dd239be1156800a1dca68520c3cfb3
      url: git@github.com:nikgraf/web-ui.git
  hop: '>=0.22.1+1 <0.22.2'

#dependencies:
#  js: any
#  unittest: any
